### ISSUE TITLE
Server is not connected

### ISSUE THREAD

**Issue by fordanic** [MIPT-Oulu/DeepKnee#10]
Pulled the latest version of the branch pypackage and ran `sh deploy.sh cpu` as is. When accessing the `ui`-service I receive a flash message saying "Server is not connected". No errors in the terminal where I started the services.

Any suggestions?

**Comment by lext** [comment]
Hi,

Could you please share more details on your setup? Specifically, docker version, docker compose and OS?

I will run this tool on a clean ubuntu machine during the weekend and will get back to this on Monday the latest. The installation tutorial will follow...

**Comment by fordanic** [comment]
Docker version 18.09.6, build 481bc77
docker-compose version 1.22.0, build f46880fe
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

**Comment by lext** [comment]
@fordanic This can be related to your PC firewall polices or the version of the system. I have just installed and tested `DeepKnee` on a installed Ubuntu 18.04 LTS (Linux Mint, in fact). You can find the installation tutorial here:

https://github.com/MIPT-Oulu/DeepKnee/blob/pypackage/INSTALLATION.md

**Comment by lext** [comment]
Since this is not progressing anywhere, I am closing teh issue.
