### ISSUE TITLE
Refactor the code into a Python package

### ISSUE THREAD

**Issue by soupault** [MIPT-Oulu/DeepKnee#3]
Including, but not limited to:
- getting rid of import magic and relative paths in https://github.com/MIPT-Oulu/DeepKnee/blob/master/inference_own/predict.py ;
- removing unused imports.

**Comment by soupault** [comment]
Done in https://github.com/MIPT-Oulu/DeepKnee/tree/pypackage.

**Comment by lext** [comment]
The inference pipeline has been hugely refactored. The traning pipeline can remain as is
