### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v

### ISSUE THREAD

**Issue by MehradAria** [MIPT-Oulu/DeepKnee#9]
Sir, I cant handle the following error when trying to test your work.
Please kindly advice. Thanks.

`(base) C:\Users\MrDig\Desktop\DeepKnee-master\own_codes>python predict.py
Version of pytorch: 1.2.0
C:\Users\MrDig\Desktop\DeepKnee-master\own_codes\model.py:32: UserWarning: nn.init.kaiming_uniform is now deprecated in favor of nn.init.kaiming_uniform_.
  nn.init.kaiming_uniform(m.weight.data)
C:\Users\MrDig\Desktop\DeepKnee-master\own_codes\model.py:36: UserWarning: nn.init.kaiming_uniform is now deprecated in favor of nn.init.kaiming_uniform_.
  nn.init.kaiming_uniform(m.weight.data)
Traceback (most recent call last):
  File "predict.py", line 68, in <module>
    tmp = load_model(snp_name, KneeNet(args.bw, 0.2, True))
  File "predict.py", line 24, in load_model
    state_dict = torch.load(filename, map_location=lambda storage, loc: storage)
  File "C:\Anaconda\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\Anaconda\lib\site-packages\torch\serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.`

**Comment by lext** [comment]
Hi, 

I do not recommend to use windows. Try on Ubuntu, it should work

**Comment by MehradAria** [comment]
> 
> 
> Hi,
> 
> I do not recommend to use windows. Try on Ubuntu, it should work

Hi there,
Thanks for the response but the same error on Ubuntu.
